import { describe, expect, it } from "vitest";
import {
  paletteMergeImageData,
  shouldMergePalette,
  PALETTE_MERGE_MAX_DELTA,
  PALETTE_MERGE_MIN_UNIQUE,
  PALETTE_MERGE_MIN_TOP16_COVERAGE,
} from "@/lib/image/paletteMerge";

function makePixels(
  width: number,
  height: number,
  fill: (x: number, y: number) => [number, number, number, number],
): Uint8ClampedArray {
  const pixels = new Uint8ClampedArray(width * height * 4);
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const [r, g, b, a] = fill(x, y);
      const i = (y * width + x) * 4;
      pixels[i] = r;
      pixels[i + 1] = g;
      pixels[i + 2] = b;
      pixels[i + 3] = a;
    }
  }
  return pixels;
}

function rgbAt(pixels: Uint8ClampedArray, x: number): [number, number, number, number] {
  const i = x * 4;
  return [pixels[i], pixels[i + 1], pixels[i + 2], pixels[i + 3]];
}

describe("paletteMergeImageData", () => {
  it("merges near-identical colors into their count-weighted mean", () => {
    // 5x1: three (4,0,32), two (4,0,24). Worst channel diff is 8, within
    // the default 12, so they merge. Mean B = (32*3 + 24*2) / 5 = 28.8,
    // rounds to 29.
    const pixels = makePixels(5, 1, (x) =>
      x < 3 ? [4, 0, 32, 255] : [4, 0, 24, 255],
    );
    const out = paletteMergeImageData(pixels, 5, 1);
    for (let x = 0; x < 5; x += 1) {
      expect(rgbAt(out, x)).toEqual([4, 0, 29, 255]);
    }
  });

  it("leaves colors farther apart than maxDelta alone", () => {
    // Worst channel diff 13 > 12: no merge.
    const pixels = makePixels(2, 1, (x) =>
      x === 0 ? [4, 0, 32, 255] : [4, 0, 19, 255],
    );
    const out = paletteMergeImageData(pixels, 2, 1);
    expect(rgbAt(out, 0)).toEqual([4, 0, 32, 255]);
    expect(rgbAt(out, 1)).toEqual([4, 0, 19, 255]);
  });

  it("respects an explicit maxDelta", () => {
    const pixels = makePixels(2, 1, (x) =>
      x === 0 ? [4, 0, 32, 255] : [4, 0, 19, 255],
    );
    // diff 13 <= 20: merge to mean (4, 0, 25.5), half-to-even rounds to 26.
    const out = paletteMergeImageData(pixels, 2, 1, 20);
    expect(rgbAt(out, 0)).toEqual([4, 0, 26, 255]);
    expect(rgbAt(out, 1)).toEqual([4, 0, 26, 255]);
  });

  it("anchors on the dominant color on count ties (lower RGB key first)", () => {
    // One pixel each of (10,10,10) and (10,10,20): tie in count, so the
    // lower key (10,10,10) anchors. Mean is (10,10,15) either way here.
    const pixels = makePixels(2, 1, (x) =>
      x === 0 ? [10, 10, 20, 255] : [10, 10, 10, 255],
    );
    const out = paletteMergeImageData(pixels, 2, 1);
    expect(rgbAt(out, 0)).toEqual([10, 10, 15, 255]);
    expect(rgbAt(out, 1)).toEqual([10, 10, 15, 255]);
  });

  it("does not chain through intermediate colors beyond the anchor", () => {
    // A=(0,0,0) x3 anchors. B=(0,0,12) x1 is within 12 of A, joins.
    // C=(0,0,24) x1 is within 12 of B but 24 from the anchor A, so it
    // stays separate (no chaining through the drifting mean).
    const pixels = makePixels(5, 1, (x) =>
      x < 3 ? [0, 0, 0, 255] : x === 3 ? [0, 0, 12, 255] : [0, 0, 24, 255],
    );
    const out = paletteMergeImageData(pixels, 5, 1);
    // Group A+B: mean B = (0*3 + 12) / 4 = 3.
    for (const x of [0, 1, 2, 3]) {
      expect(rgbAt(out, x)).toEqual([0, 0, 3, 255]);
    }
    expect(rgbAt(out, 4)).toEqual([0, 0, 24, 255]);
  });

  it("leaves non-opaque pixels untouched", () => {
    // Semi-transparent near-duplicate of the opaque color: the opaque
    // pixels merge among themselves, the translucent pixel keeps RGB.
    const pixels = makePixels(3, 1, (x) =>
      x === 0 ? [4, 0, 32, 255] : x === 1 ? [4, 0, 24, 255] : [4, 0, 28, 128],
    );
    const out = paletteMergeImageData(pixels, 3, 1);
    expect(rgbAt(out, 0)).toEqual([4, 0, 28, 255]);
    expect(rgbAt(out, 1)).toEqual([4, 0, 28, 255]);
    expect(rgbAt(out, 2)).toEqual([4, 0, 28, 128]);
  });

  it("returns single-color input unchanged", () => {
    const pixels = makePixels(4, 1, () => [7, 7, 7, 255]);
    const out = paletteMergeImageData(pixels, 4, 1);
    expect(Array.from(out)).toEqual(Array.from(pixels));
  });

  it("matches parity.py _palette_merge_rgba byte-identical on a mixed case", () => {
    // Cross-check against the harness (values generated by running
    // parity._palette_merge_rgba on this exact pixel buffer at
    // max_delta=12). If this drifts, the harness stops measuring the
    // shipped behavior.
    const pixels = makePixels(8, 1, (x) =>
      x < 3
        ? [4, 0, 32, 255]
        : x < 5
          ? [4, 0, 24, 255]
          : x < 7
            ? [250, 250, 250, 255]
            : [4, 0, 28, 128],
    );
    const out = paletteMergeImageData(pixels, 8, 1, 12);
    // Dark group: (4,0,32)x3 + (4,0,24)x2 -> mean (4, 0, 28.8) -> 29.
    const expected: Array<[number, number, number, number]> = [
      [4, 0, 29, 255],
      [4, 0, 29, 255],
      [4, 0, 29, 255],
      [4, 0, 29, 255],
      [4, 0, 29, 255],
      [250, 250, 250, 255],
      [250, 250, 250, 255],
      [4, 0, 28, 128],
    ];
    for (let x = 0; x < 8; x += 1) {
      expect(rgbAt(out, x)).toEqual(expected[x]);
    }
  });

  it("exports the shipped default delta", () => {
    expect(PALETTE_MERGE_MAX_DELTA).toBe(12);
  });
});

describe("shouldMergePalette", () => {
  // Deterministic unique color for index k (k < 65536): no collisions.
  function uniqueColor(k: number): [number, number, number, number] {
    return [k % 256, Math.floor(k / 256) % 256, 255, 255];
  }

  it("fires on many unique colors with a concentrated palette", () => {
    // 360x100 = 36000 pixels: 16 colors at 1000 pixels each
    // (top-16 coverage 16000/36000 = 0.444) plus 20000 unique
    // single-pixel colors. Distinct = 20016 >= 20000, coverage
    // 0.444 >= 0.40, so the gate fires.
    const pixels = makePixels(360, 100, (x, y) => {
      const idx = y * 360 + x;
      if (idx < 16000) {
        const c = Math.floor(idx / 1000);
        return [c * 16, 200, 100, 255];
      }
      return uniqueColor(idx - 16000);
    });
    expect(shouldMergePalette(pixels, 360, 100)).toBe(true);
  });

  it("stays off when there are too few unique colors", () => {
    // Concentrated palette (16 colors covering 100%) but only 16
    // distinct colors: fails the count leg.
    const pixels = makePixels(100, 100, (x, y) => {
      const c = Math.floor((y * 100 + x) / 625);
      return [c * 16, 200, 100, 255];
    });
    expect(shouldMergePalette(pixels, 100, 100)).toBe(false);
  });

  it("stays off when the palette is diffuse", () => {
    // 36000 distinct single-pixel colors: top-16 coverage 16/36000
    // is far below 0.40, fails the coverage leg.
    const pixels = makePixels(360, 100, (x, y) =>
      uniqueColor(y * 360 + x),
    );
    expect(shouldMergePalette(pixels, 360, 100)).toBe(false);
  });

  it("ignores non-opaque pixels", () => {
    // 10000 opaque concentrated pixels plus 30000 non-opaque unique
    // colors: opaque distinct is 16, so the gate stays off even
    // though the total distinct count exceeds the threshold.
    const pixels = makePixels(200, 200, (x, y) => {
      const idx = y * 200 + x;
      if (idx < 10000) {
        const c = Math.floor(idx / 625);
        return [c * 16, 200, 100, 255];
      }
      const [r, g, b] = uniqueColor(idx - 10000);
      return [r, g, b, 128];
    });
    expect(shouldMergePalette(pixels, 200, 200)).toBe(false);
  });

  it("exports the shipped gate thresholds", () => {
    expect(PALETTE_MERGE_MIN_UNIQUE).toBe(20000);
    expect(PALETTE_MERGE_MIN_TOP16_COVERAGE).toBe(0.4);
  });
});
